BeMatch:
- changed-files:
  - any-glob-to-any-file:
    - App/BeMatch/**
    - Packages/BeMatch/**
    - BeMatch.xcworkspace/**

FlyCam:
- changed-files:
  - any-glob-to-any-file:
    - App/FlyCam/**
    - Packages/FlyCam/**
    - FlyCam.xcworkspace/**

SDK:
- changed-files:
  - any-glob-to-any-file:
    - Packages/SDK/**
    - SDK.xcworkspace/**
